name: Ontology update testing

on:
  repository_dispatch:
    types: [ new-release ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
          ref: ${{ github.head_ref }}

      # get latest release tag on the SBOL-visual repository
      - name: Get latest release of SBOL Visual from payload
        id: tag-version
        run: |
          [[ ! ${{ github.event.client_payload.ref }} =~ refs/tags ]] && exit
          REF_TAG=${{ github.event.client_payload.ref }}
          echo "TAG_VAL=${REF_TAG##*/}" >> $GITHUB_ENV

        # check if tag released is of the verified format e.g. *.*
      - name: Check tag for release type
        id: check-tag
        run: |
          if [[ ${{ env.TAG_VAL }} =~ [0-9]+\.[0-9]+\.?[0-9]?$ ]]; then
              echo "RELEASE_TYPE=true" >> $GITHUB_ENV
          else
             echo "RELEASE_TYPE=false" >> $GITHUB_ENV
          fi

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      # python dependencies for markdown-to-owl are installed
      - name: Install python dependencies
        run: |
          cd markdown-to-owl
          pip3 install owlready2
          pip3 install rdflib

      # maven dependencies for LODE installed
      - name: Install LODE dependencies
        run: |
          cd LODE
          mvn clean install

      # maven dependencies for lode-document-extractor installed
      - name: Install maven dependencies
        run: |
          cd lode-document-extractor
          mvn clean install

      # maven dependencies for sbol-vo-update-doc are installed
      - name: Install maven dependencies
        run: |
          cd sbol-vo-update-doc
          mvn clean install

      # create temporary folder for html and rdf files
      - name: create temporary folder
        run: |
          mkdir -p temp_files
          cp -u ./sbol-vo.html ./sbol-vo.rdf ./sbol-vo.txt   ./temp_files
          cp -u -r ./Glyphs ./temp_files

      # create glyph folder for use within python scripts (needs changing to support non release glyphs
      - name: create default Glyph folder
        run: |
          svn export --force https://github.com/jakezion/SBOL-visual-test/tags/${{ env.TAG_VAL }}/Glyphs

      # scripts are called in succession: 1. rdf file is updated 2. HTML file is created with default values 3. updated rdf file is used to update HTML file
      - name: Generate new ontology values
        run: |
          cd markdown-to-owl
          python Application.py

          cd ../lode-document-extractor
          mvn exec:java -Dexec.mainClass="lodedocumentextractor"

          cd ../sbol-vo-update-doc
          mvn exec:java -e -Dexec.mainClass="uk.ac.keele.dissys.sbolvo.html.App"

        # updated are committed and pushed to the repository on current branch (looping doesnt occur due to limitations in github actions)
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: test update test update
