name: Ontology update testing

on:
  release:
    types: [ published ]

jobs:
  build_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install python dependencies
        run: |
          cd markdown-to-owl
          pip3 install owlready2
          pip3 install rdflib

      - name: Install maven dependencies
        run: |
          cd lode-document-extractor
          mvn clean install

      - name: Install maven dependencies
        run: |
          cd sbol-vo-update-doc
          mvn clean install

      - name: Generate new ontology values
        run: |
          cd markdown-to-owl
          python Application.py

          cd ../lode-document-extractor
          mvn exec:java -Dexec.mainClass="lodedocumentextractor"

          cd ../sbol-vo-update-doc
          mvn exec:java -e -Dexec.mainClass="uk.ac.keele.dissys.sbolvo.html.App"

      - name: View html
        run: |
          sudo apt-get install html2text
          html2text sbol-vo.html | less
