name: Ontology update testing

on:
  push:
    branches: [ feature/sbolvo31 ]
  pull_request:
    branches: [ feature/sblvo31 ]

jobs:
  build_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install python dependencies
        run: |
          pip3 install owlready2
          pip3 install rdflib
          python Application.py

      - name: Install sbol-vo dependencies
        run: |
          cd lode-document-extractor
          mvn clean install
          mvn exec:java -Dexec.mainClass="lodedocumentextractor"

      - name: Install sbol-vo dependencies
        run: |
          cd sbol-vo-update-doc
          mvn clean install
          mvn exec:java -e -Dexec.mainClass="uk.ac.keele.dissys.sbolvo.html.App"



