name: Ontology update testing

on:
  push:
    branches: [ feature/sbolvo31 ]
  pull_request:
    branches: [ feature/sblvo31 ]
  release:
    types: [ published ]
    tags:
      - 'v*.*'

jobs:
  build_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}


      - name: Get latest release of SBOL Visual
        uses: rez0n/actions-github-release@main
        id: sbol-visual-release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "SynBioDex/SBOL-visual"
          type: "stable"

      - name: Test2
        run: echo ${{ steps.sbol-visual-release.outputs.release }}

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install python dependencies
        run: |
          cd markdown-to-owl
          pip3 install owlready2
          pip3 install rdflib


      - name: Install maven dependencies
        run: |
          cd lode-document-extractor
          mvn clean install

      - name: Cache lode-document-extractor Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('lode-document-extractor/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install maven dependencies
        run: |
          cd sbol-vo-update-doc
          mvn clean install

      - name: Cache sbol-vo-update-doc Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('sbol-vo-update-doc/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate new ontology values
        run: |
          cd markdown-to-owl
          python Application.py

          cd ../lode-document-extractor
          mvn exec:java -Dexec.mainClass="lodedocumentextractor"

          cd ../sbol-vo-update-doc
          mvn exec:java -e -Dexec.mainClass="uk.ac.keele.dissys.sbolvo.html.App"

      - name: create and populate version folder
        run: |
          mkdir -p versions/${{ env.RELEASE_VERSION }}
          cp ./sbol-vo.html ./versions/${{ env.RELEASE_VERSION }}
          cp ./sbol-vo.rdf ./versions/${{ env.RELEASE_VERSION }}
          cp https://github.com/SynBioDex/SBOL-visual/${{ env.RELEASE_VERSION }}/Glyphs ./versions/${{ env.RELEASE_VERSION }}/Glyphs

        if: ${{ github.event_name == 'published' }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          tagging_message: ${{ steps.sbol-visual-release.outputs.release }}
          commit_message: Created new versions folder and updated default html and rdf file




