name: Java CI with Maven

on:
  push:
    branches: [ feature/sbolvo31 ]
  pull_request:
    branches: [ feature/sblvo31 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip3 install owlready2
          pip3 install rdflib
          mvn clean install -f sbol-vo-update-doc/pom.xml

      - name: Update ontology values
        run: |
          ls -la
          python markdown-to-owl/Application.py
          ls -la

      - name: update HTML ontology file
        run: mvn exec:java -Dexec.mainClass="uk.ac.keele.dissys.sbolvo.html.App"

